//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppObjectFinder.WsEntities {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8080/Wcf_ObjectFinder/Servicio/", ConfigurationName="WsEntities.IWsObjectFinder")]
    public interface IWsObjectFinder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Usuario", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_UsuarioResp" +
            "onse")]
        void Crear_Usuario(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Usuario", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_UsuarioResp" +
            "onse")]
        System.Threading.Tasks.Task Crear_UsuarioAsync(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Usuari" +
            "o", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Usuari" +
            "oResponse")]
        void Actualizar_Usuario(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Usuari" +
            "o", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Usuari" +
            "oResponse")]
        System.Threading.Tasks.Task Actualizar_UsuarioAsync(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Registro", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_RegistroRes" +
            "ponse")]
        void Crear_Registro(LogicaObjectFinder.WsObjectfinder.entRegistro Registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Registro", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_RegistroRes" +
            "ponse")]
        System.Threading.Tasks.Task Crear_RegistroAsync(LogicaObjectFinder.WsObjectfinder.entRegistro Registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Objeto", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_ObjetoRespo" +
            "nse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LogicaObjectFinder.WsObjectfinder.entMedia))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="idObjeto")]
        int Crear_Objeto(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Objeto", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_ObjetoRespo" +
            "nse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="idObjeto")]
        System.Threading.Tasks.Task<int> Crear_ObjetoAsync(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Objeto" +
            "", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Objeto" +
            "Response")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LogicaObjectFinder.WsObjectfinder.entMedia))]
        void Actualizar_Objeto(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Objeto" +
            "", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Objeto" +
            "Response")]
        System.Threading.Tasks.Task Actualizar_ObjetoAsync(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Notificacio" +
            "n", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Notificacio" +
            "nResponse")]
        void Crear_Notificacion(LogicaObjectFinder.WsObjectfinder.entNotificacion Notificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Notificacio" +
            "n", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Notificacio" +
            "nResponse")]
        System.Threading.Tasks.Task Crear_NotificacionAsync(LogicaObjectFinder.WsObjectfinder.entNotificacion Notificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Media", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_MediaRespon" +
            "se")]
        void Crear_Media(LogicaObjectFinder.WsObjectfinder.entMedia Media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Media", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_MediaRespon" +
            "se")]
        System.Threading.Tasks.Task Crear_MediaAsync(LogicaObjectFinder.WsObjectfinder.entMedia Media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Media", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_MediaR" +
            "esponse")]
        void Actualizar_Media(LogicaObjectFinder.WsObjectfinder.entMedia Media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Media", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_MediaR" +
            "esponse")]
        System.Threading.Tasks.Task Actualizar_MediaAsync(LogicaObjectFinder.WsObjectfinder.entMedia Media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Categoria", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_CategoriaResp" +
            "onse")]
        LogicaObjectFinder.WsObjectfinder.entCategoria[] Get_Categoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Categoria", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_CategoriaResp" +
            "onse")]
        System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entCategoria[]> Get_CategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Estado", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_EstadoRespons" +
            "e")]
        LogicaObjectFinder.WsObjectfinder.entEstado[] Get_Estado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Estado", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_EstadoRespons" +
            "e")]
        System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entEstado[]> Get_EstadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Facultad", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_FacultadRespo" +
            "nse")]
        LogicaObjectFinder.WsObjectfinder.entFacultad[] Get_Facultad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Facultad", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_FacultadRespo" +
            "nse")]
        System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entFacultad[]> Get_FacultadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_MediaxObjeto", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_MediaxObjetoR" +
            "esponse")]
        LogicaObjectFinder.WsObjectfinder.entMedia[] Get_MediaxObjeto(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_MediaxObjeto", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_MediaxObjetoR" +
            "esponse")]
        System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entMedia[]> Get_MediaxObjetoAsync(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Notificacion", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_NotificacionR" +
            "esponse")]
        LogicaObjectFinder.WsObjectfinder.entNotificacion[] Get_Notificacion(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Notificacion", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_NotificacionR" +
            "esponse")]
        System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entNotificacion[]> Get_NotificacionAsync(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Objeto_All", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Objeto_AllRes" +
            "ponse")]
        LogicaObjectFinder.WsObjectfinder.entObjeto[] Get_Objeto_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Objeto_All", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Objeto_AllRes" +
            "ponse")]
        System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entObjeto[]> Get_Objeto_AllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Media_All", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Media_AllResp" +
            "onse")]
        LogicaObjectFinder.WsObjectfinder.entMedia[] Get_Media_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Media_All", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Media_AllResp" +
            "onse")]
        System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entMedia[]> Get_Media_AllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Usuario", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_UsuarioRespon" +
            "se")]
        LogicaObjectFinder.WsObjectfinder.entUsuario[] Get_Usuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Usuario", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_UsuarioRespon" +
            "se")]
        System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entUsuario[]> Get_UsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_ObjetoxUsuari" +
            "o", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_ObjetoxUsuari" +
            "oResponse")]
        LogicaObjectFinder.WsObjectfinder.entObjeto[] Get_ObjetoxUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_ObjetoxUsuari" +
            "o", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_ObjetoxUsuari" +
            "oResponse")]
        System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entObjeto[]> Get_ObjetoxUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_Objetos_A" +
            "ll", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_Objetos_A" +
            "llResponse")]
        int Get_Nro_Objetos_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_Objetos_A" +
            "ll", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_Objetos_A" +
            "llResponse")]
        System.Threading.Tasks.Task<int> Get_Nro_Objetos_AllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_Objetos", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_ObjetosRe" +
            "sponse")]
        int Get_Nro_Objetos(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_Objetos", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_ObjetosRe" +
            "sponse")]
        System.Threading.Tasks.Task<int> Get_Nro_ObjetosAsync(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Objeto", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_ObjetoRespons" +
            "e")]
        LogicaObjectFinder.WsObjectfinder.entObjeto[] Get_Objeto(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Objeto", ReplyAction="http://localhost:8080/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_ObjetoRespons" +
            "e")]
        System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entObjeto[]> Get_ObjetoAsync(int idEstado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsObjectFinderChannel : AppObjectFinder.WsEntities.IWsObjectFinder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsObjectFinderClient : System.ServiceModel.ClientBase<AppObjectFinder.WsEntities.IWsObjectFinder>, AppObjectFinder.WsEntities.IWsObjectFinder {
        
        public WsObjectFinderClient() {
        }
        
        public WsObjectFinderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsObjectFinderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsObjectFinderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsObjectFinderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Crear_Usuario(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario) {
            base.Channel.Crear_Usuario(Usuario);
        }
        
        public System.Threading.Tasks.Task Crear_UsuarioAsync(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario) {
            return base.Channel.Crear_UsuarioAsync(Usuario);
        }
        
        public void Actualizar_Usuario(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario) {
            base.Channel.Actualizar_Usuario(Usuario);
        }
        
        public System.Threading.Tasks.Task Actualizar_UsuarioAsync(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario) {
            return base.Channel.Actualizar_UsuarioAsync(Usuario);
        }
        
        public void Crear_Registro(LogicaObjectFinder.WsObjectfinder.entRegistro Registro) {
            base.Channel.Crear_Registro(Registro);
        }
        
        public System.Threading.Tasks.Task Crear_RegistroAsync(LogicaObjectFinder.WsObjectfinder.entRegistro Registro) {
            return base.Channel.Crear_RegistroAsync(Registro);
        }
        
        public int Crear_Objeto(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto) {
            return base.Channel.Crear_Objeto(Objeto);
        }
        
        public System.Threading.Tasks.Task<int> Crear_ObjetoAsync(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto) {
            return base.Channel.Crear_ObjetoAsync(Objeto);
        }
        
        public void Actualizar_Objeto(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto) {
            base.Channel.Actualizar_Objeto(Objeto);
        }
        
        public System.Threading.Tasks.Task Actualizar_ObjetoAsync(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto) {
            return base.Channel.Actualizar_ObjetoAsync(Objeto);
        }
        
        public void Crear_Notificacion(LogicaObjectFinder.WsObjectfinder.entNotificacion Notificacion) {
            base.Channel.Crear_Notificacion(Notificacion);
        }
        
        public System.Threading.Tasks.Task Crear_NotificacionAsync(LogicaObjectFinder.WsObjectfinder.entNotificacion Notificacion) {
            return base.Channel.Crear_NotificacionAsync(Notificacion);
        }
        
        public void Crear_Media(LogicaObjectFinder.WsObjectfinder.entMedia Media) {
            base.Channel.Crear_Media(Media);
        }
        
        public System.Threading.Tasks.Task Crear_MediaAsync(LogicaObjectFinder.WsObjectfinder.entMedia Media) {
            return base.Channel.Crear_MediaAsync(Media);
        }
        
        public void Actualizar_Media(LogicaObjectFinder.WsObjectfinder.entMedia Media) {
            base.Channel.Actualizar_Media(Media);
        }
        
        public System.Threading.Tasks.Task Actualizar_MediaAsync(LogicaObjectFinder.WsObjectfinder.entMedia Media) {
            return base.Channel.Actualizar_MediaAsync(Media);
        }
        
        public LogicaObjectFinder.WsObjectfinder.entCategoria[] Get_Categoria() {
            return base.Channel.Get_Categoria();
        }
        
        public System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entCategoria[]> Get_CategoriaAsync() {
            return base.Channel.Get_CategoriaAsync();
        }
        
        public LogicaObjectFinder.WsObjectfinder.entEstado[] Get_Estado() {
            return base.Channel.Get_Estado();
        }
        
        public System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entEstado[]> Get_EstadoAsync() {
            return base.Channel.Get_EstadoAsync();
        }
        
        public LogicaObjectFinder.WsObjectfinder.entFacultad[] Get_Facultad() {
            return base.Channel.Get_Facultad();
        }
        
        public System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entFacultad[]> Get_FacultadAsync() {
            return base.Channel.Get_FacultadAsync();
        }
        
        public LogicaObjectFinder.WsObjectfinder.entMedia[] Get_MediaxObjeto(int idObjeto) {
            return base.Channel.Get_MediaxObjeto(idObjeto);
        }
        
        public System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entMedia[]> Get_MediaxObjetoAsync(int idObjeto) {
            return base.Channel.Get_MediaxObjetoAsync(idObjeto);
        }
        
        public LogicaObjectFinder.WsObjectfinder.entNotificacion[] Get_Notificacion(int idObjeto) {
            return base.Channel.Get_Notificacion(idObjeto);
        }
        
        public System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entNotificacion[]> Get_NotificacionAsync(int idObjeto) {
            return base.Channel.Get_NotificacionAsync(idObjeto);
        }
        
        public LogicaObjectFinder.WsObjectfinder.entObjeto[] Get_Objeto_All() {
            return base.Channel.Get_Objeto_All();
        }
        
        public System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entObjeto[]> Get_Objeto_AllAsync() {
            return base.Channel.Get_Objeto_AllAsync();
        }
        
        public LogicaObjectFinder.WsObjectfinder.entMedia[] Get_Media_All() {
            return base.Channel.Get_Media_All();
        }
        
        public System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entMedia[]> Get_Media_AllAsync() {
            return base.Channel.Get_Media_AllAsync();
        }
        
        public LogicaObjectFinder.WsObjectfinder.entUsuario[] Get_Usuario() {
            return base.Channel.Get_Usuario();
        }
        
        public System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entUsuario[]> Get_UsuarioAsync() {
            return base.Channel.Get_UsuarioAsync();
        }
        
        public LogicaObjectFinder.WsObjectfinder.entObjeto[] Get_ObjetoxUsuario(int idUsuario) {
            return base.Channel.Get_ObjetoxUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entObjeto[]> Get_ObjetoxUsuarioAsync(int idUsuario) {
            return base.Channel.Get_ObjetoxUsuarioAsync(idUsuario);
        }
        
        public int Get_Nro_Objetos_All() {
            return base.Channel.Get_Nro_Objetos_All();
        }
        
        public System.Threading.Tasks.Task<int> Get_Nro_Objetos_AllAsync() {
            return base.Channel.Get_Nro_Objetos_AllAsync();
        }
        
        public int Get_Nro_Objetos(int idEstado) {
            return base.Channel.Get_Nro_Objetos(idEstado);
        }
        
        public System.Threading.Tasks.Task<int> Get_Nro_ObjetosAsync(int idEstado) {
            return base.Channel.Get_Nro_ObjetosAsync(idEstado);
        }
        
        public LogicaObjectFinder.WsObjectfinder.entObjeto[] Get_Objeto(int idEstado) {
            return base.Channel.Get_Objeto(idEstado);
        }
        
        public System.Threading.Tasks.Task<LogicaObjectFinder.WsObjectfinder.entObjeto[]> Get_ObjetoAsync(int idEstado) {
            return base.Channel.Get_ObjetoAsync(idEstado);
        }
    }
}
