//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaObjectFinder.WsObjectfinder {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entUsuario", Namespace="http://schemas.datacontract.org/2004/07/Entities_ObjectFinder.Usuario")]
    [System.SerializableAttribute()]
    public partial class entUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string celularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string generoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idIntegracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                if ((object.ReferenceEquals(this.celularField, value) != true)) {
                    this.celularField = value;
                    this.RaisePropertyChanged("celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                if ((object.ReferenceEquals(this.claveField, value) != true)) {
                    this.claveField = value;
                    this.RaisePropertyChanged("clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((this.fechaNacimientoField.Equals(value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                if ((this.fechaRegistroField.Equals(value) != true)) {
                    this.fechaRegistroField = value;
                    this.RaisePropertyChanged("fechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string genero {
            get {
                return this.generoField;
            }
            set {
                if ((object.ReferenceEquals(this.generoField, value) != true)) {
                    this.generoField = value;
                    this.RaisePropertyChanged("genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                if ((this.idEstadoField.Equals(value) != true)) {
                    this.idEstadoField = value;
                    this.RaisePropertyChanged("idEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idIntegracion {
            get {
                return this.idIntegracionField;
            }
            set {
                if ((this.idIntegracionField.Equals(value) != true)) {
                    this.idIntegracionField = value;
                    this.RaisePropertyChanged("idIntegracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primerApellidoField, value) != true)) {
                    this.primerApellidoField = value;
                    this.RaisePropertyChanged("primerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primerNombre {
            get {
                return this.primerNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.primerNombreField, value) != true)) {
                    this.primerNombreField = value;
                    this.RaisePropertyChanged("primerNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoApellidoField, value) != true)) {
                    this.segundoApellidoField = value;
                    this.RaisePropertyChanged("segundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoNombreField, value) != true)) {
                    this.segundoNombreField = value;
                    this.RaisePropertyChanged("segundoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entRegistro", Namespace="http://schemas.datacontract.org/2004/07/Entities_ObjectFinder.Registro")]
    [System.SerializableAttribute()]
    public partial class entRegistro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idFacultadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idObjetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                if ((this.idEstadoField.Equals(value) != true)) {
                    this.idEstadoField = value;
                    this.RaisePropertyChanged("idEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFacultad {
            get {
                return this.idFacultadField;
            }
            set {
                if ((this.idFacultadField.Equals(value) != true)) {
                    this.idFacultadField = value;
                    this.RaisePropertyChanged("idFacultad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idObjeto {
            get {
                return this.idObjetoField;
            }
            set {
                if ((this.idObjetoField.Equals(value) != true)) {
                    this.idObjetoField = value;
                    this.RaisePropertyChanged("idObjeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionField, value) != true)) {
                    this.observacionField = value;
                    this.RaisePropertyChanged("observacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entObjeto", Namespace="http://schemas.datacontract.org/2004/07/Entities_ObjectFinder.Objeto")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicaObjectFinder.WsObjectfinder.entMedia))]
    public partial class entObjeto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idObjetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreObjetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string palabrasClavesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                if ((this.idEstadoField.Equals(value) != true)) {
                    this.idEstadoField = value;
                    this.RaisePropertyChanged("idEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idObjeto {
            get {
                return this.idObjetoField;
            }
            set {
                if ((this.idObjetoField.Equals(value) != true)) {
                    this.idObjetoField = value;
                    this.RaisePropertyChanged("idObjeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreObjeto {
            get {
                return this.nombreObjetoField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreObjetoField, value) != true)) {
                    this.nombreObjetoField = value;
                    this.RaisePropertyChanged("nombreObjeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string palabrasClaves {
            get {
                return this.palabrasClavesField;
            }
            set {
                if ((object.ReferenceEquals(this.palabrasClavesField, value) != true)) {
                    this.palabrasClavesField = value;
                    this.RaisePropertyChanged("palabrasClaves");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entMedia", Namespace="http://schemas.datacontract.org/2004/07/Entities_ObjectFinder.Media")]
    [System.SerializableAttribute()]
    public partial class entMedia : LogicaObjectFinder.WsObjectfinder.entObjeto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idMediaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idObjeto1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] imagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoImagenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMedia {
            get {
                return this.idMediaField;
            }
            set {
                if ((this.idMediaField.Equals(value) != true)) {
                    this.idMediaField = value;
                    this.RaisePropertyChanged("idMedia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="idObjeto")]
        public int idObjeto1 {
            get {
                return this.idObjeto1Field;
            }
            set {
                if ((this.idObjeto1Field.Equals(value) != true)) {
                    this.idObjeto1Field = value;
                    this.RaisePropertyChanged("idObjeto1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreImagen {
            get {
                return this.nombreImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreImagenField, value) != true)) {
                    this.nombreImagenField = value;
                    this.RaisePropertyChanged("nombreImagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoImagen {
            get {
                return this.tipoImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoImagenField, value) != true)) {
                    this.tipoImagenField = value;
                    this.RaisePropertyChanged("tipoImagen");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entNotificacion", Namespace="http://schemas.datacontract.org/2004/07/Entities_ObjectFinder.Notificacion")]
    [System.SerializableAttribute()]
    public partial class entNotificacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaNotificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idNotificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idObjetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeNotificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNotificacion {
            get {
                return this.fechaNotificacionField;
            }
            set {
                if ((this.fechaNotificacionField.Equals(value) != true)) {
                    this.fechaNotificacionField = value;
                    this.RaisePropertyChanged("fechaNotificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idNotificacion {
            get {
                return this.idNotificacionField;
            }
            set {
                if ((this.idNotificacionField.Equals(value) != true)) {
                    this.idNotificacionField = value;
                    this.RaisePropertyChanged("idNotificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idObjeto {
            get {
                return this.idObjetoField;
            }
            set {
                if ((this.idObjetoField.Equals(value) != true)) {
                    this.idObjetoField = value;
                    this.RaisePropertyChanged("idObjeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensajeNotificacion {
            get {
                return this.mensajeNotificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeNotificacionField, value) != true)) {
                    this.mensajeNotificacionField = value;
                    this.RaisePropertyChanged("mensajeNotificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entCategoria", Namespace="http://schemas.datacontract.org/2004/07/Entities_ObjectFinder.Categoria")]
    [System.SerializableAttribute()]
    public partial class entCategoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_CATEGORIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRE_CATEGORIAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_CATEGORIA {
            get {
                return this.ID_CATEGORIAField;
            }
            set {
                if ((this.ID_CATEGORIAField.Equals(value) != true)) {
                    this.ID_CATEGORIAField = value;
                    this.RaisePropertyChanged("ID_CATEGORIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE_CATEGORIA {
            get {
                return this.NOMBRE_CATEGORIAField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRE_CATEGORIAField, value) != true)) {
                    this.NOMBRE_CATEGORIAField = value;
                    this.RaisePropertyChanged("NOMBRE_CATEGORIA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entEstado", Namespace="http://schemas.datacontract.org/2004/07/Entities_ObjectFinder.Estado")]
    [System.SerializableAttribute()]
    public partial class entEstado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRE_ESTADOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ESTADO {
            get {
                return this.ID_ESTADOField;
            }
            set {
                if ((this.ID_ESTADOField.Equals(value) != true)) {
                    this.ID_ESTADOField = value;
                    this.RaisePropertyChanged("ID_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE_ESTADO {
            get {
                return this.NOMBRE_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRE_ESTADOField, value) != true)) {
                    this.NOMBRE_ESTADOField = value;
                    this.RaisePropertyChanged("NOMBRE_ESTADO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entFacultad", Namespace="http://schemas.datacontract.org/2004/07/Entities_ObjectFinder.Facultad")]
    [System.SerializableAttribute()]
    public partial class entFacultad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_FACULTADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_LOCALIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRE_FACULTADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_FACULTAD {
            get {
                return this.ID_FACULTADField;
            }
            set {
                if ((this.ID_FACULTADField.Equals(value) != true)) {
                    this.ID_FACULTADField = value;
                    this.RaisePropertyChanged("ID_FACULTAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_LOCALIDAD {
            get {
                return this.ID_LOCALIDADField;
            }
            set {
                if ((this.ID_LOCALIDADField.Equals(value) != true)) {
                    this.ID_LOCALIDADField = value;
                    this.RaisePropertyChanged("ID_LOCALIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE_FACULTAD {
            get {
                return this.NOMBRE_FACULTADField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRE_FACULTADField, value) != true)) {
                    this.NOMBRE_FACULTADField = value;
                    this.RaisePropertyChanged("NOMBRE_FACULTAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:51565/Wcf_ObjectFinder/Servicio/", ConfigurationName="WsObjectfinder.IWsObjectFinder")]
    public interface IWsObjectFinder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Usuario", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_UsuarioRes" +
            "ponse")]
        void Crear_Usuario(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Usuario", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_UsuarioRes" +
            "ponse")]
        System.Threading.Tasks.Task Crear_UsuarioAsync(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Usuar" +
            "io", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Usuar" +
            "ioResponse")]
        void Actualizar_Usuario(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Usuar" +
            "io", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Usuar" +
            "ioResponse")]
        System.Threading.Tasks.Task Actualizar_UsuarioAsync(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Registro", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_RegistroRe" +
            "sponse")]
        void Crear_Registro(LogicaObjectFinder.WsObjectfinder.entRegistro Registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Registro", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_RegistroRe" +
            "sponse")]
        System.Threading.Tasks.Task Crear_RegistroAsync(LogicaObjectFinder.WsObjectfinder.entRegistro Registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Objeto", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_ObjetoResp" +
            "onse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="idObjeto")]
        int Crear_Objeto(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Objeto", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_ObjetoResp" +
            "onse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="idObjeto")]
        System.Threading.Tasks.Task<int> Crear_ObjetoAsync(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Objet" +
            "o", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Objet" +
            "oResponse")]
        void Actualizar_Objeto(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Objet" +
            "o", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Objet" +
            "oResponse")]
        System.Threading.Tasks.Task Actualizar_ObjetoAsync(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Notificaci" +
            "on", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Notificaci" +
            "onResponse")]
        void Crear_Notificacion(LogicaObjectFinder.WsObjectfinder.entNotificacion Notificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Notificaci" +
            "on", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Notificaci" +
            "onResponse")]
        System.Threading.Tasks.Task Crear_NotificacionAsync(LogicaObjectFinder.WsObjectfinder.entNotificacion Notificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Media", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_MediaRespo" +
            "nse")]
        void Crear_Media(LogicaObjectFinder.WsObjectfinder.entMedia Media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_Media", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Crear_MediaRespo" +
            "nse")]
        System.Threading.Tasks.Task Crear_MediaAsync(LogicaObjectFinder.WsObjectfinder.entMedia Media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Media" +
            "", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Media" +
            "Response")]
        void Actualizar_Media(LogicaObjectFinder.WsObjectfinder.entMedia Media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Media" +
            "", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Actualizar_Media" +
            "Response")]
        System.Threading.Tasks.Task Actualizar_MediaAsync(LogicaObjectFinder.WsObjectfinder.entMedia Media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Categoria", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_CategoriaRes" +
            "ponse")]
        System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entCategoria> Get_Categoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Categoria", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_CategoriaRes" +
            "ponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entCategoria>> Get_CategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Estado", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_EstadoRespon" +
            "se")]
        System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entEstado> Get_Estado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Estado", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_EstadoRespon" +
            "se")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entEstado>> Get_EstadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Facultad", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_FacultadResp" +
            "onse")]
        System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entFacultad> Get_Facultad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Facultad", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_FacultadResp" +
            "onse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entFacultad>> Get_FacultadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_MediaxObjeto" +
            "", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_MediaxObjeto" +
            "Response")]
        System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entMedia> Get_MediaxObjeto(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_MediaxObjeto" +
            "", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_MediaxObjeto" +
            "Response")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entMedia>> Get_MediaxObjetoAsync(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Notificacion" +
            "", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Notificacion" +
            "Response")]
        System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entNotificacion> Get_Notificacion(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Notificacion" +
            "", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Notificacion" +
            "Response")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entNotificacion>> Get_NotificacionAsync(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Objeto_All", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Objeto_AllRe" +
            "sponse")]
        System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entObjeto> Get_Objeto_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Objeto_All", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Objeto_AllRe" +
            "sponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entObjeto>> Get_Objeto_AllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Media_All", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Media_AllRes" +
            "ponse")]
        System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entMedia> Get_Media_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Media_All", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Media_AllRes" +
            "ponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entMedia>> Get_Media_AllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Usuario", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_UsuarioRespo" +
            "nse")]
        System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entUsuario> Get_Usuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Usuario", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_UsuarioRespo" +
            "nse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entUsuario>> Get_UsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_ObjetoxUsuar" +
            "io", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_ObjetoxUsuar" +
            "ioResponse")]
        System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entObjeto> Get_ObjetoxUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_ObjetoxUsuar" +
            "io", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_ObjetoxUsuar" +
            "ioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entObjeto>> Get_ObjetoxUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_Objetos_" +
            "All", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_Objetos_" +
            "AllResponse")]
        int Get_Nro_Objetos_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_Objetos_" +
            "All", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_Objetos_" +
            "AllResponse")]
        System.Threading.Tasks.Task<int> Get_Nro_Objetos_AllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_Objetos", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_ObjetosR" +
            "esponse")]
        int Get_Nro_Objetos(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_Objetos", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Nro_ObjetosR" +
            "esponse")]
        System.Threading.Tasks.Task<int> Get_Nro_ObjetosAsync(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Objeto", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_ObjetoRespon" +
            "se")]
        System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entObjeto> Get_Objeto(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_Objeto", ReplyAction="http://localhost:51565/Wcf_ObjectFinder/Servicio/IWsObjectFinder/Get_ObjetoRespon" +
            "se")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entObjeto>> Get_ObjetoAsync(int idEstado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsObjectFinderChannel : LogicaObjectFinder.WsObjectfinder.IWsObjectFinder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsObjectFinderClient : System.ServiceModel.ClientBase<LogicaObjectFinder.WsObjectfinder.IWsObjectFinder>, LogicaObjectFinder.WsObjectfinder.IWsObjectFinder {
        
        public WsObjectFinderClient() {
        }
        
        public WsObjectFinderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsObjectFinderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsObjectFinderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsObjectFinderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Crear_Usuario(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario) {
            base.Channel.Crear_Usuario(Usuario);
        }
        
        public System.Threading.Tasks.Task Crear_UsuarioAsync(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario) {
            return base.Channel.Crear_UsuarioAsync(Usuario);
        }
        
        public void Actualizar_Usuario(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario) {
            base.Channel.Actualizar_Usuario(Usuario);
        }
        
        public System.Threading.Tasks.Task Actualizar_UsuarioAsync(LogicaObjectFinder.WsObjectfinder.entUsuario Usuario) {
            return base.Channel.Actualizar_UsuarioAsync(Usuario);
        }
        
        public void Crear_Registro(LogicaObjectFinder.WsObjectfinder.entRegistro Registro) {
            base.Channel.Crear_Registro(Registro);
        }
        
        public System.Threading.Tasks.Task Crear_RegistroAsync(LogicaObjectFinder.WsObjectfinder.entRegistro Registro) {
            return base.Channel.Crear_RegistroAsync(Registro);
        }
        
        public int Crear_Objeto(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto) {
            return base.Channel.Crear_Objeto(Objeto);
        }
        
        public System.Threading.Tasks.Task<int> Crear_ObjetoAsync(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto) {
            return base.Channel.Crear_ObjetoAsync(Objeto);
        }
        
        public void Actualizar_Objeto(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto) {
            base.Channel.Actualizar_Objeto(Objeto);
        }
        
        public System.Threading.Tasks.Task Actualizar_ObjetoAsync(LogicaObjectFinder.WsObjectfinder.entObjeto Objeto) {
            return base.Channel.Actualizar_ObjetoAsync(Objeto);
        }
        
        public void Crear_Notificacion(LogicaObjectFinder.WsObjectfinder.entNotificacion Notificacion) {
            base.Channel.Crear_Notificacion(Notificacion);
        }
        
        public System.Threading.Tasks.Task Crear_NotificacionAsync(LogicaObjectFinder.WsObjectfinder.entNotificacion Notificacion) {
            return base.Channel.Crear_NotificacionAsync(Notificacion);
        }
        
        public void Crear_Media(LogicaObjectFinder.WsObjectfinder.entMedia Media) {
            base.Channel.Crear_Media(Media);
        }
        
        public System.Threading.Tasks.Task Crear_MediaAsync(LogicaObjectFinder.WsObjectfinder.entMedia Media) {
            return base.Channel.Crear_MediaAsync(Media);
        }
        
        public void Actualizar_Media(LogicaObjectFinder.WsObjectfinder.entMedia Media) {
            base.Channel.Actualizar_Media(Media);
        }
        
        public System.Threading.Tasks.Task Actualizar_MediaAsync(LogicaObjectFinder.WsObjectfinder.entMedia Media) {
            return base.Channel.Actualizar_MediaAsync(Media);
        }
        
        public System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entCategoria> Get_Categoria() {
            return base.Channel.Get_Categoria();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entCategoria>> Get_CategoriaAsync() {
            return base.Channel.Get_CategoriaAsync();
        }
        
        public System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entEstado> Get_Estado() {
            return base.Channel.Get_Estado();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entEstado>> Get_EstadoAsync() {
            return base.Channel.Get_EstadoAsync();
        }
        
        public System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entFacultad> Get_Facultad() {
            return base.Channel.Get_Facultad();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entFacultad>> Get_FacultadAsync() {
            return base.Channel.Get_FacultadAsync();
        }
        
        public System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entMedia> Get_MediaxObjeto(int idObjeto) {
            return base.Channel.Get_MediaxObjeto(idObjeto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entMedia>> Get_MediaxObjetoAsync(int idObjeto) {
            return base.Channel.Get_MediaxObjetoAsync(idObjeto);
        }
        
        public System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entNotificacion> Get_Notificacion(int idObjeto) {
            return base.Channel.Get_Notificacion(idObjeto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entNotificacion>> Get_NotificacionAsync(int idObjeto) {
            return base.Channel.Get_NotificacionAsync(idObjeto);
        }
        
        public System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entObjeto> Get_Objeto_All() {
            return base.Channel.Get_Objeto_All();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entObjeto>> Get_Objeto_AllAsync() {
            return base.Channel.Get_Objeto_AllAsync();
        }
        
        public System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entMedia> Get_Media_All() {
            return base.Channel.Get_Media_All();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entMedia>> Get_Media_AllAsync() {
            return base.Channel.Get_Media_AllAsync();
        }
        
        public System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entUsuario> Get_Usuario() {
            return base.Channel.Get_Usuario();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entUsuario>> Get_UsuarioAsync() {
            return base.Channel.Get_UsuarioAsync();
        }
        
        public System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entObjeto> Get_ObjetoxUsuario(int idUsuario) {
            return base.Channel.Get_ObjetoxUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entObjeto>> Get_ObjetoxUsuarioAsync(int idUsuario) {
            return base.Channel.Get_ObjetoxUsuarioAsync(idUsuario);
        }
        
        public int Get_Nro_Objetos_All() {
            return base.Channel.Get_Nro_Objetos_All();
        }
        
        public System.Threading.Tasks.Task<int> Get_Nro_Objetos_AllAsync() {
            return base.Channel.Get_Nro_Objetos_AllAsync();
        }
        
        public int Get_Nro_Objetos(int idEstado) {
            return base.Channel.Get_Nro_Objetos(idEstado);
        }
        
        public System.Threading.Tasks.Task<int> Get_Nro_ObjetosAsync(int idEstado) {
            return base.Channel.Get_Nro_ObjetosAsync(idEstado);
        }
        
        public System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entObjeto> Get_Objeto(int idEstado) {
            return base.Channel.Get_Objeto(idEstado);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LogicaObjectFinder.WsObjectfinder.entObjeto>> Get_ObjetoAsync(int idEstado) {
            return base.Channel.Get_ObjetoAsync(idEstado);
        }
    }
}
